import type { Song } from "@/entities/song";

export const mockSongs: Song[] = [
  {
    id: 1,
    title: "Midnight Echoes",
    artist: "Neon Harbor",
    album: "City After Dark",
    genre: "Synthwave",
    coverUrl: "https://picsum.photos/seed/song1/300/300",
  },
  {
    id: 2,
    title: "Golden Skies",
    artist: "Avery Lane",
    album: "Sunset Polaroids",
    genre: "Indie Pop",
    coverUrl: "https://picsum.photos/seed/song2/300/300",
  },
  {
    id: 3,
    title: "Rust & Reverie",
    artist: "Iron Vale",
    album: "Mechanical Hearts",
    genre: "Alternative Rock",
    coverUrl: "https://picsum.photos/seed/song3/300/300",
  },
  {
    id: 4,
    title: "Ocean Glass",
    artist: "Luma Tide",
    album: "Driftwood Dreams",
    genre: "Ambient",
    coverUrl: "https://picsum.photos/seed/song4/300/300",
  },
  {
    id: 5,
    title: "Velvet Lights",
    artist: "The Afterhours",
    album: "Neon Lounge",
    genre: "R&B",
    coverUrl: "https://picsum.photos/seed/song5/300/300",
  },
  {
    id: 6,
    title: "Paper Planets",
    artist: "Orbit Kids",
    album: "Gravity Games",
    genre: "Electropop",
    coverUrl: "https://picsum.photos/seed/song6/300/300",
  },
  {
    id: 7,
    title: "Wildflower Run",
    artist: "Juniper Vale",
    album: "Open Roads",
    genre: "Folk",
    coverUrl: "https://picsum.photos/seed/song7/300/300",
  },
  {
    id: 8,
    title: "Static Bloom",
    artist: "Signal Fires",
    album: "Frequency",
    genre: "Electronic",
    coverUrl: "https://picsum.photos/seed/song8/300/300",
  },
  {
    id: 9,
    title: "Crimson Lines",
    artist: "North Arcade",
    album: "Late Train Home",
    genre: "Indie Rock",
    coverUrl: "https://picsum.photos/seed/song9/300/300",
  },
  {
    id: 10,
    title: "Silver Morning",
    artist: "Harbor Choir",
    album: "First Light",
    genre: "Dream Pop",
    coverUrl: "https://picsum.photos/seed/song10/300/300",
  },
];
